object Constant {
  val MOBILE_EVENT_TO_HOME_SHOW_MAPPING = Map(
    "device_type" -> "device_type",
    "sdk_ver" -> "sdk_ver",
    "channel_code" -> "channel_code",
    "app_ver" -> "app_ver",
    "sys_ver" -> "sys_ver",
    "uid" -> "uid",
    "open_udid" -> "open_udid",
    "launch_guid" -> "launch_guid",
    "idfa" -> "idfa",
    "idfv" -> "idfv",
    "device_token" -> "device_token",
    "event_code" -> "event_code",
    "event_guid" -> "event_guid",
    "net" -> "net",
    "day_first" -> "day_first",
    "day_before" -> "day_before",
    "channel_origin" -> "channel_origin",
    "event_time" -> "event_time",
    "ctime" -> "ctime",
    "client_ip" -> "client_ip",
    "datetime" -> "datetime",
    "ip_server" -> "ip_server",
    "app_code" -> "app_code",
    "attr" -> "attr",
    "mfwuuid" -> "mfwuuid",
    "lat" -> "lat",
    "lng" -> "lng",
    "uri" -> "uri",
    "ref" -> "ref",
    "puri" -> "puri",
    "hour" -> "hour",
    "umddid" -> "umddid",
    "hardware_model" -> "ardware_model",
    "android_id" -> "android_id",
    "mfw_did" -> "mfw_did",
    "get_json_object(attr, '$.item_title')" -> "attr_item_title",
    "get_json_object(attr, '$.item_index')" -> "attr_item_index",
    "get_json_object(attr, '$.item_business_id')" -> "attr_item_business_id",
    "get_json_object(attr, '$.item_url')"	-> "attr_item_url",
    "get_json_object(attr, '$.item_type')" -> "attr_item_type",
    "get_json_object(attr, '$.abtest')" -> "attr_abtest",
    "get_json_object(attr, '$.abtest_type')" -> "attr_abtest_type",
    "get_json_object(attr, '$._tp')" -> "attr__tp",
    "get_json_object(attr, '$._tpt')" -> "attr__tpt",
    "get_json_object(attr, '$._tl')"  -> "attr__tl",
    "get_json_object(attr, '$._tpa')" -> "attr__tpa",
    "get_json_object(attr, '$._tid')" -> "attr__tid",
    "get_json_object(attr, '$._tpre')" -> "attr__tpre",
    "get_json_object(attr, '$._tps')" -> "attr__tps",
    "dt" -> "dt"
  )
}
